name: "Terraform Destroy"

on: 
  workflow_dispatch:

env:
  AWS_REGION: 'ap-northeast-1'
  ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_ARN }}
  BUCKET_NAME: ${{ secrets.S3_BUCKET }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: |
          terraform init \
            -migrate-state \
            -backend-config="bucket=${{ env.BUCKET_NAME }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=ap-northeast-1"
          
      - name: Terraform destroy
        run: |
          terraform destroy -auto-approve