name: "Terraform CI/CD"

on: 
  push:
  workflow_dispatch:
    inputs:
      apply:
        description: "Terraform applyの確認"
        required: true
        type: boolean
        default: false

env:
  AWS_REGION: 'ap-northeast-1'
  ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_ARN }}
  BUCKET_NAME: ${{ secrets.S3_BUCKET }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev
    env:
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_shomotsu_acm_id: ${{ secrets.SHOMOTSU_ACM_ID }}
      TF_VAR_image_acm_domain: ${{ secrets.IMAGE_ACM_DOMAIN }}
      TF_VAR_dbpassword_name: ${{ secrets.DBPASSWORD_NAME }}
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_rds_username_paramete_name: ${{ secrets.RDS_USERNAME_PARAMETE_NAME }}
      TF_VAR_rds_dbname_parameter_name: ${{ secrets.RDS_DBNAME_PARAMETER_NAME }}
      TF_VAR_rds_parameter_name: ${{ secrets.RDS_PARAMETER_NAME }}
      TF_VAR_route53_domain_name: ${{ secrets.ROUTE53_DOMAIN_NAME }}
      TF_VAR_bucket_source_arn: ${{ secrets.BUCKET_SOURCE_ARN }}
      TF_VAR_env_s3: ${{ secrets.ENV_S3 }}
      TF_VAR_laravel_container_image: ${{ secrets.LARAVEL_CONTAINER_IMAGE }}
      TF_VAR_nginx_container_image: ${{ secrets.NGINX_CONTAINER_IMAGE }}
      TF_VAR_execution_role_arn: ${{ secrets.EXECUTION_ROLE_ARN }}
      TF_VAR_task_role_arn: ${{ secrets.TASK_ROLE_ARN }}
      
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: |
          terraform init \
            -migrate-state \
            -backend-config="bucket=${{ env.BUCKET_NAME }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=ap-northeast-1"
          
      - name: Terraform fmt
        run: |
          terraform fmt

      - name: Terraform validate
        run: |
          terraform validate

      - name: Terraform plan
        run: |
          terraform plan -out=tfplan

      - name: Terraform apply
        run: |
          terraform apply -auto-approve