name: "Terraform CI/CD"

on: 
  workflow_dispatch:
    inputs:
      apply:
        description: "Terraform applyの確認"
        required: true
        type: boolean
        default: false

env:
  AWS_REGION: 'ap-northeast-1'
  ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_ARN }}
  BUCKET_NAME: ${{ secrets.S3_BUCKET }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev // 実行したいmain.tfがあるフォルダを指定する。

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: |
          terraform init \
            -migrate-state \
            -backend-config="bucket=${{ env.BUCKET_NAME }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=ap-northeast-1"
          
      - name: Terraform fmt
        run: |
          terraform fmt -check

      - name: Terraform validate
        run: |
          terraform validate

      - name: Terraform plan
        run: |
          terraform plan -out=tfplan

      - name: Terraform apply
        if: ${{ inputs.apply == true }}
        run: |
          terraform apply -auto-approve